server:
  port: 3000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: root!@

  servlet:
    multipart:
      enabled: true # 멀티파트 업로드를 활성화한다.
      file-size-threshold: 2KB # 보조기억장치에 파일을 쓰기 시작하는 임계값이다.
      max-file-size: 100MB # 단일 파일의 최대 크기이다.
      max-request-size: 120MB # 단일 요청의 최대 크기이다.
    
  jwt:
    secret: d00928033e0288ff7f810733c98d38ed904f613cacfbe6c5677899aaa60e71a0
    expiration: 3600000
 
  # Spring Boot 3(Hibernate 6 사용.) 이후로 Hibernate 방언을 선택 사항으로 사용할 수 있다. 
  # Hibernate 6은 classpath에 추가한 드라이버 의존성에 기반하여 자동으로 방언을 구성한다.
  jpa:
    hibernate:
      ddl-auto: create # 테이블이 데이터베이스에 존재하지 않으면 생성한다.
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

springdoc:
  version: 1.0
  api-docs:
    path: /api-docs
            
file:
  upload:
    path: ./upload # 디렉터리에서 파일을 저장할 경로이다.