server:
  port: 3000

spring:
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: root!@
    
#  elasticsearch:
#    uris:
#    - localhost:9200

  servlet:
    multipart:
      enabled: true # 멀티파트 업로드를 활성화한다.
      file-size-threshold: 2KB # 보조기억장치에 파일을 쓰기 시작하는 임계값이다.
      max-file-size: 100MB # 단일 파일의 최대 크기이다.
      max-request-size: 120MB # 단일 요청의 최대 크기이다.
      
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: aaaa
            client-secret: aaaa
            redirect-uri: http://localhost:3000/api/v1/oauth2/code/google
            scope: email, profile
            
          naver:
            client-id: aaaa
            client-secret: aaaa
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/api/v1/oauth2/code/naver
            scope: name, email
            client-name: Naver
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  web:
    resources:
      static-locations:
      - classpath:/templates/
            
#  mvc:
#    view:
#      suffix: .html
    
  jwt:
    secret: d00928033e0288ff7f810733c98d38ed904f613cacfbe6c5677899aaa60e71a0
    expiration: 3600000
 
  # Spring Boot 3(Hibernate 6 사용.) 이후로 Hibernate 방언을 선택 사항으로 사용할 수 있다. 
  # Hibernate 6은 classpath에 추가한 드라이버 의존성에 기반하여 자동으로 방언을 구성한다.
  jpa:
    hibernate:
      ddl-auto: create # 테이블이 데이터베이스에 존재하지 않으면 생성한다.
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

springdoc:
  version: 1.0
  api-docs:
    path: /api-docs
            
file:
  upload:
    path: ./upload # 디렉터리에서 파일을 저장할 경로이다.